/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Greeter } from "./Greeter";
export type { Player } from "./Player";
export * as factories from "./factories";
export { Greeter__factory } from "./factories/Greeter__factory";
export { Player__factory } from "./factories/Player__factory";
