/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as achallengeGuessTheNumberSol from "./Achallenge.guess-the-number.sol";
export type { achallengeGuessTheNumberSol };
import type * as afactoryGuessTheNumberSol from "./Afactory.guess-the-number.sol";
export type { afactoryGuessTheNumberSol };
