/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ICTF, ICTFInterface } from "../ICTF";

const _abi = [
  {
    inputs: [],
    name: "isComplete",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICTF__factory {
  static readonly abi = _abi;
  static createInterface(): ICTFInterface {
    return new utils.Interface(_abi) as ICTFInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ICTF {
    return new Contract(address, _abi, signerOrProvider) as ICTF;
  }
}
