/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as achallengeGuessTheNumberSol from "./Achallenge.guess-the-number.sol";
export * as afactoryGuessTheNumberSol from "./Afactory.guess-the-number.sol";
